### ISSUE TITLE
[3.0.24] Broken for Python 3 / ModuleNotFoundError: No module named 'logmod'

### ISSUE THREAD

**Issue by hartwork** [dieseldev/diesel#104]
```console
# cd "$(mktemp -d)"                        

# virtualenv fooo

# python --version
Python 3.6.6

# source fooo/bin/activate

# pip install https://github.com/dieseldev/diesel/archive/master.tar.gz
[..]
Successfully installed Jinja2-2.10 MarkupSafe-1.1.0 Werkzeug-0.14.1 asn1crypto-0.24.0 cffi-1.11.5 click-7.0 cryptography-2.4.2 diesel-3.0.24 dnspython-1.16.0 flask-1.0.2 greenlet-0.4.15 http-parser-0.8.3 idna-2.8 itsdangerous-1.1.0 pycparser-2.19 pyopenssl-18.0.0 six-1.12.0 twiggy-0.4.7

# python -c 'import diesel'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/tmp.3TqpDbqaeU/fooo/lib/python3.6/site-packages/diesel/__init__.py", line 2, in <module>
    from logmod import log, levels as loglevels, set_log_level
ModuleNotFoundError: No module named 'logmod'
```

The `from logmod` would ne to be `from diesel.logmod` I believe.

Related: #95

**Comment by hartwork** [comment]
Closing to keep https://github.com/issues clean for myself…
